#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# This script installs an application template to your project.
# Run this script using ./download-and-install-template. Expected to be run
# from the project's root directory.
#
# Positional parameters:
#   template_name (required) – the name of the template to install
#   app_name (required) – the name of the application
# -----------------------------------------------------------------------------
set -euo pipefail

template_name=$1
# Use shell parameter expansion to get the last word, where the delimiter between
# words is `-`.
# See https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Shell-Parameter-Expansion
template_short_name="app-${template_name##*-}"
app_name=$2

curr_dir=$(pwd)

cd "${template_name}"

if [ "${template_short_name}" != "${app_name}" ]; then
  echo "Modifying template to use ${app_name} instead of ${template_short_name}..."
  curl "https://raw.githubusercontent.com/navapbc/${template_name}/rocket/rename-warning/template-only-bin/rename-template-app" | bash -s -- "${template_short_name}" "${app_name}"
fi

# Note: Keep this list in sync with the files listed in update-template
# Copy only relevant files that should be included in the project repo.
echo "Copying files from ${template_name}..."
# Copy top level paths.
cp -r \
  .grype.yml \
  "${app_name}" \
  docker-compose.yml \
  docker-compose.mock-production.yml \
  ${curr_dir}
# Copy nested paths. Make any missing directories.
mkdir -p "${curr_dir}/.github/workflows" && cp ".github/workflows/ci-${app_name}.yml" "${curr_dir}/.github/workflows"
mkdir -p "${curr_dir}/docs" && cp -r "docs/${app_name}" "${curr_dir}/docs"

cd - >& /dev/null